project:
  type: website
  output-dir: docs

website:
  title: "Kimberlee Wong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Resources.qmd
        text: Resources

format:
  html:
    theme: 
      light: morph
      dark: darkly
    css: styles.css
    toc: false

editor: visual

